### ISSUE TITLE
Beschrijving voor ActivityDefinition.isActive lijkt niet correct

### ISSUE THREAD

**Issue by janwijbrand** [Koppeltaal/Koppeltaal-Architectuur#11]
Onder https://vzvz.gitbook.io/koppeltaal-1-3-architectuur/technologie-architectuur#activitydefinition-other staat bij `ActivityDefinition.isActive` de beschrijving "The person that is normally responsible for performing this activity.". Dit lijkt me niet juist. Mag ik vragen dit te corrigeren?

**Comment by bmstibbe** [comment]
Hoe wordt het ActivityDefinition.isActive element gebruikt in KT 1.3.x?
Bij de ActivityDefinition STU3 bestaat geen "isActive" element, maar wel een "status" element. 

Volgens mij is : "ActivityDefinition.isActive=true (DSTU1) gelijk aan "ActivityDefinition.status"="active" (STU3)

Is de volgende beschrijving dan wel correct: 
 ActivityDefinition.isActive : "Only an active activity can be performed"

**Comment by janwijbrand** [comment]
@bmstibbe `ActivityDefinition.isActive` is een extensie op DSTU1, en dus //niet// hetzelfde als `ActivityDefinition.status`. De waarde voor `isActive`zie je ook terug in de UI van de KT server. Mij vraag is slechts om de documentatie te fixen. `isActive` geeft aan dat een AD wel of niet meer actief in te zetten is.

**Comment by bmstibbe** [comment]
@janwijbrand ik heb, vorig jaar, de documentatie ,mbt de `isActive` element definitie aangepast in: "Indicates if the activity is active."
