### ISSUE TITLE
Er mist een overzicht van alle Koppeltaal servers en wat hun doel is

### ISSUE THREAD

**Issue by JorisHeadease** [Koppeltaal/Koppeltaal-Architectuur#14]
Wellicht goed om een aparte pagina te maken met alle omgevingen. Handig voor nieuwe ontwikkelaars om te weten welke omgevingen er zijn voor welk doel.

Waarschijnlijk is deze documentatie er al; in dat geval is het waarschijnlijk handiger om deze hier aan toe te voegen.

**Comment by bmstibbe** [comment]
@JorisEdia ,

Nieuwe pagina toegevoegd "Opbouw Koppeltaal Server" waarin beschreven wordt de verschillende Koppeltaal omgevingen.
Zie: https://vzvz.gitbook.io/koppeltaal-1-3-architectuur/opbouw-koppeltaal-server

**Comment by JorisHeadease** [comment]
@bmstibbe ik doelde vooral op de omgevingen zoals bijv edge, stable, prd, etc.

Zo kan de ontwikkelaar zien welke omgevingen er zijn en wanneer welke omgeving gebruikt dient te worden.

**Comment by bmstibbe** [comment]
Koppeltaal Server omgevingen + URLs toegevoegd, zie https://vzvz.gitbook.io/koppeltaal-1-3-architectuur/opbouw-koppeltaal-server#koppeltaal-omgeving-urls

**Comment by JorisHeadease** [comment]
@bmstibbe dank! Kan je nog toevoegen wat het doel is van de omgeving? Zo is het bijvoorbeeld duidelijk wat het verschil is tussen Acceptatie en Stable.

**Comment by bmstibbe** [comment]
Done. Zie omschrijvingen in https://vzvz.gitbook.io/koppeltaal-1-3-architectuur/opbouw-koppeltaal-server#koppeltaal-omgeving-urls.

**Comment by JorisHeadease** [comment]
Super, dank @bmstibbe!
