### ISSUE TITLE
Onduidelijkheid in bericht versturen/ophalen

### ISSUE THREAD

**Issue by JorisHeadease** [Koppeltaal/Koppeltaal-Architectuur#15]
In de documentatie staan de volgende stukken:

> Bericht versturen
Alle applicaties maken gebruik van de standaard HTTP operatie POST om berichten (FHIR Message DSTU1) te versturen. De berichten worden naar een vaste endpoint (URL) van Koppeltaal gestuurd, zie 'interactie ontvangen' (technische service) waarvan de basis URL bijvoorbeeld https://koppeltaal.nl/FHIR/Koppeltaal/Mailbox is.

> Bericht ophalen
Alle applicaties maken gebruik van de standaard HTTP operatie GET om berichten (FHIR Message DSTU1) op te halen. De berichten kunnen van een vaste endpoint (URL) bij Koppeltaal opgehaald worden, zie 'interactie ophalen' (technische service) waarvan de basis URL bijvoorbeeld https://koppeltaal.nl/FHIR/Koppeltaal/MessageHeader is.

Hierbij wordt gerefeerd naar `'interactie ontvangen' (technische service)` en `'interactie ophalen' (technische service)`. Wat wordt hier precies mee bedoeld? Het is voor nieuwe ontwikkelaars nu erg onduidelijk dat de URL eigenlijk altijd `<KOPPELTAAL_URL>/FHIR/Koppeltaal/Mailbox` & `<KOPPELTAAL_URL>/FHIR/Koppeltaal/MessageHeader` moet zijn, waarbij KOPPELTAAL_URL refereert naar documentatie die nog toegevoegd moet worden (zie #14).

**Comment by bmstibbe** [comment]
@JorisEdia . Ben vergeten voor de verschillende omgevingen de <Koppeltaal__url> toe te voegen. Ik ga hier achteraan en voeg dit toe in de documentatie.

**Comment by JorisHeadease** [comment]
Ah in #14 bedoel je? Vergeet mijn comment in dat geval! 👍

**Comment by bmstibbe** [comment]
Referentie linkjes gelegd naar: https://vzvz.gitbook.io/koppeltaal-1-3-architectuur/opbouw-koppeltaal-server#koppeltaal-omgeving-urls voor beide voorbeelden.
