### ISSUE TITLE
Bernard, nog een testje

### ISSUE THREAD

**Issue by flameling** [Koppeltaal/Koppeltaal-Architectuur#2]
Deze mag gelijk gesloten worden. @bmstibbe

**Comment by bmstibbe** [comment]
@flameling  dit issue #2 wordt gesloten. Bedankt voor de uitvoerige test.

**Comment by flameling** [comment]
Hertest dit keer met assign

**Comment by bmstibbe** [comment]
Labels en Prjects toegevoegd.
