### ISSUE TITLE
Incorrecte links in Leeswijzer

### ISSUE THREAD

**Issue by janwijbrand** [Koppeltaal/Koppeltaal-Architectuur#3]
De drie links in de paragraaf Leeswijzer (Bedrijfsarch., Informatiesystemen arch. en Technologie arch.) wijzen (nog?) naar https://stibbe.gitbook.io/koppeltaal-1-3-x-architectuur/...

**Comment by janwijbrand** [comment]
Ik zie dat veel andere links die verwijzing zijn binnen de documentatie (nog) naar het stibbe.gitbook.io domain wijzen.

**Comment by bmstibbe** [comment]
De linkjes zijn aangepast. Alle linkjes in de documentatie relatief gemaakt. Ze verwijzen nu allemaal naar:
https://vzvz.gitbook.io/koppeltaal-1-3-architectuur/...
