### ISSUE TITLE
Links in FHIR Resources hoofdstuk wijzen nog naar oude docs 

### ISSUE THREAD

**Issue by janwijbrand** [Koppeltaal/Koppeltaal-Architectuur#4]
Onder https://vzvz.gitbook.io/koppeltaal-1-3-architectuur/technologie-architectuur#fhir-resources staatn verschillende links die nog uitkomen op https://www.koppeltaal.nl/release-13. Zoals bv. voor MessageEvents.

**Comment by bmstibbe** [comment]
Alle Binding linkjes aangepast, door ze relatief te maken.
Vb Binding: MessageEvents -> https://vzvz.gitbook.io/koppeltaal-1-3-architectuur/technologie-architectuur#messageevents
