### ISSUE TITLE
In de SSO flow is het opgeven van een careplan activity optioneel

### ISSUE THREAD

**Issue by janwijbrand** [Koppeltaal/Koppeltaal-Architectuur#5]
In https://vzvz.gitbook.io/koppeltaal-1-3-architectuur/technologie-architectuur#de-single-sign-on-sso-flow wordt uitgelegd dat voor een launch request je een Application id, Patient id, User id en een activity id moet opgeven. Zo staat dat overigens ook in de oude docs gemoemd.

De activity id echter is optioneel. En door aan te geven dat het optioneel is, is het duidelijk dat je ook kunt SSOen om bij een specifieke patient uit te komen zonder dat deze een activity nodig heeft.

**Comment by bmstibbe** [comment]
De tekst in https://vzvz.gitbook.io/koppeltaal-1-3-architectuur/technologie-architectuur#de-single-sign-on-sso-flow aangepast.
CarePlanActivity identifier is nu een optionele parameter bij SSO.

**Comment by janwijbrand** [comment]
Top!

Suggestie: Ik zie onder bullet point 4 ook "optionele" velden vermeld. Misschien horen die ook in de nieuwe sectie over optionele velden?

**Comment by bmstibbe** [comment]
Gedaan. Bedankt voor de vermelding.
