### ISSUE TITLE
RelatedPerson.relationship Binding URL

### ISSUE THREAD

**Issue by janwijbrand** [Koppeltaal/Koppeltaal-Architectuur#7]
On https://vzvz.gitbook.io/koppeltaal-1-3-architectuur/technologie-architectuur#relatedperson the URL to the relationship binding is pointing to http://hl7.org/fhir/vs/relatedperson-relationshiptype, which points nowhere. I think the intention was to point to http://hl7.org/fhir/DSTU1/valueset-relatedperson-relationshiptype.html instead? Can this be corrected?

**Comment by janwijbrand** [comment]
Er zijn nog een paar "broken" referenties naar Bindings:

`CarePlan.status`
http://hl7.org/fhir/care-plan-status → http://hl7.org/fhir/DSTU1/care-plan-status.html

`CarePlan.goal.status`
http://hl7.org/fhir/care-plan-goal-status → http://hl7.org/fhir/DSTU1/care-plan-goal-status.html

`Patient.gender and RelatedPerson.gender`
http://hl7.org/fhir/dSTU1/valueset-administrative-gender → http://hl7.org/fhir/DSTU1/valueset-administrative-gender.html

**Comment by bmstibbe** [comment]
Fixed.
